### ISSUE TITLE
Нужна ли в приложении проверка wi-fi? 

### ISSUE THREAD

**Issue by igor-dyatlov** [mosmetro-android/mosmetro-android#129]
Можно было прикрутить SnackBar с оповещением если зашел в приложение, а wi-fi не включил (интересно у меня одного такое было?) но SnackBar доступен только с api23..(или support-compat уже умеет это на других версиях?)

**Comment by TheDrHax** [comment]
Речь идёт про простую проверку состояния Wi-Fi в главном меню? Не думаю, что эта функция очень уж нужна. Хотя можно просто Toast вывести, это две строчки кода займёт.

**Comment by Venique** [comment]
А можно добавить немного иной вариант проверки Wi-Fi? Чтобы при включенной проверке приложение не давало подключаться "транспортным" сетям (MT_Free etc). Часто сталкиваюсь с проблемой, что идет коннект к сетям проезжающих мимо автобусов, например. И ладно, если капчи нет (хоть окно с её вводом можно и отключить), но сам по себе коннект достаточно длительный и интернет просто пропадает. Особенно мешает, если за рулем и используешь навигатор, например. Приходится каждый раз выключать вафлю, что не очень удобно. В дополнение можно было бы сделать двойной виджет - одним ползунком включается подключение к этим сетям, а вторым включается автоматическая авторизация в этих сетях. 

Провел опрос среди коллег, которые пользуются приложением и сделал вывод, что данная функция достаточно востребована, а ставить и настраивать отдельное приложение для игнорирования определенных сетей не каждый хочет (а с отдельным виджетом таких и нет вовсе).

**Comment by labdsf** [comment]
@Venique есть похожий баг #70

**Comment by TheDrHax** [comment]
Думаю, что проверка всё-таки не нужна. По задумке приложение само не активируется без Wi-Fi, а ручное подключение работает не обращая внимание на сеть, чтобы дать возможность подключиться владельцам странных прошивок, возвращающих "<unknown network>" или "0x" какие-нибудь.

**Comment by Venique** [comment]
А если wi-fi включен постоянно просто потому, что зачем его каждый раз
туда-сюда дергать? В таком случае, телефон упорно подключается к, например,
проезжающим мимо автобусам и если не может пройти авторизацию (а у меня она
только в ручном режиме), то интернет тупо пропадает. В итоге рядом с
дорогами находиться невозможно. Этого можно было бы избежать, если бы
приложение делало проверку названия сети и не позволяло бы подключаться к
сети MosGorTrans, к примеру.

То есть речь не о подключении в плане авторизации, а о подключении в прямом
смысле, чтобы сам телефон физически не подключался к определенной сети.
