### ISSUE TITLE
Блокировка доступа в интернет из-за приложения

### ISSUE THREAD

**Issue by trykovyura** [mosmetro-android/mosmetro-android#156]
Сеть начала определять программу и блокировать доступ к интернету.

**Comment by alexeyknyshev** [comment]
Пример

7 Сен 2017 г. 9:30 пользователь "trykovyura" <notifications@github.com>
написал:

**Comment by TheDrHax** [comment]
Капчу отключили, осталась только заглушка.

Пример страницы: https://auth.wi-fi.ru/auto_auth

**Comment by trykovyura** [comment]
Сеть MosMetro_Free
![screenshot_2017-09-07-08-36-43-599_com android chrome](https://user-images.githubusercontent.com/920793/30149643-1247116c-93b1-11e7-9321-f4e310167c3a.png)

**Comment by uburuntu** [comment]
Есть идеи как обойти?

Не знаю насколько в тему, но GameGuardian генерит рандомное название пакета и, соответственно, банальными способами приложение не отследить.

Но с каких пор вай-фай может чекнуть приложение? Может благодаря открытости кода смогли какие-то специфичные паттерны пакетов определить.

**Comment by TheDrHax** [comment]
Название пакета никак не светится в сети. Они определяют приложение по каким-то косвенным признакам (заголовки HTTP, скорость отправки запроса, отличия от браузера, ...). Т.е. если отключить его в настройках, то они никак о нём не узнают.

**Comment by artbear** [comment]
Также сегодня неожиданно на это нарвался :(
Готов потестировать исправление косвенных признаков

**Comment by artbear** [comment]
>Т.е. если отключить его в настройках, то они никак о нём не узнают.

@TheDrHax расшифруйте этот ответ, пожалуйста.

**Comment by TheDrHax** [comment]
@artbear В приложении в главном меню есть кнопка "Автоматическая авторизация". Если её отключить, то о приложении никак не узнать из самой сети. Просто оно не будет проявлять никакой активности и всё.

**Comment by artbear** [comment]
@TheDrHax ну т.е. это равносильно удалению приложения, с точки зрения выполнения его рабочих функций.
как временный выход может устроить.

но к хорошему быстро привык, хочется вернуть простую авторизацию без рекламы и тормозов от текущего продукта :)

**Comment by hell03end** [comment]
@TheDrHax Отключение автоматической авторизации не решило вопрос.

**Comment by TheDrHax** [comment]
@hell03end Если бан уже получен, то только ждать. Отключение предотвращает блокировку, а не отменяет её.

**Comment by hell03end** [comment]
@TheDrHax Автоматическое подключение изначально было отключено, т.е. ручное подключение приводит к тому же результату.

**Comment by rlex** [comment]
На 4пда люди ловят баны даже без приложения. Максима опять "постаралась"

**Comment by bam80** [comment]
@rlex, без приложения это как?

**Comment by Chubukov-Aleksey** [comment]
@bam80
то есть без установленного приложения на устройстве. Я до некоторой поры логинился через браузер с баннерорезкой и однажды словил капчу. Психаную и таки установил приложение.

Есть у меня ничем не подтвержденная теория, что максимка режет доступ рандомно из списка юзеров, приносящих меньше нужного дохода с рекламы.

**Comment by rlex** [comment]
Не первый раз. Когда сделали anti-adblock, под раздачу тоже попадали все подряд, даже те кто про адблок не слышал.

**Comment by Chubukov-Aleksey** [comment]
Хотя я могу еще предположить, что просто _работники_ рута и pcap-а просто тырят мак-адреса окружающего народа и тем самым невинные устройства оказываются в бане. </конспирология>

**Comment by alexeyknyshev** [comment]
Смысл тырить окружающего, это сложно и не очень понятен смысл. Они
выставляют MAC рандомно скорее всего, и вероятность попадания даже в
человека часто бывающего в метро весьма низкая.

7 Сен 2017 г. 17:04 пользователь "Aleksey Chubukov" <
notifications@github.com> написал:

**Comment by uburuntu** [comment]
Кто-нибудь пробовал сменить mac-адрес для снятия бана? Или бан по номеру телефону у них?

**Comment by TheDrHax** [comment]
@uburuntu Устройство связано с сетью только MAC адресом. Номер телефона они узнают именно по MAC. Т.е. таким образом можно полностью менять свой идентификатор

**Comment by uburuntu** [comment]
@TheDrHax, да, про это в курсе. Но при первом подключении нового мак-адреса требуется же регистрация по номеру телефона. И если с мак-адресом блокируется номер телефона, то обход сменой мака не получится.

Я попробую через часик прокатиться с измененным маком. Мб временный вариант обхода удастся.

**Comment by uburuntu** [comment]
Странно.
Менял мак-адреса, вай-фай вовсе не коннектил.
Потом вернул свой изначальный и почему-то стал разбаненным, хотя 24 часа не прошло. А забаниться снова у меня не вышло.
Непонятный эксперимент вышел, но такое чувство, что они ослабили строгость блокировки.

**Comment by TheDrHax** [comment]
@uburuntu Всё вернулось как было до этого. Похоже, это был такой весёлый тест.

**Comment by splincode** [comment]
Да даже если они ослабили блокировку или провели такой тест, нужно серьезно задуматься, нужно разработчикам приложения воспроизвести подобную ситуацию, попытаться как-то иначе коннектиться к сети, а то жалко как-то получать бан на 24 часа и потом отключать у приложения автоматическое подключение . А в целом приложение крутое, ничего не скажу..

**Comment by trykovyura** [comment]
Бан автоматически снялся через 24 часа. Ездил пол недели с ручным, остальную часть с автоподключением. Бан больше не ловил. 
Теорию с мак адресом не удалось проверить. Но имхо не выход менять мак адрес, если их алгоритм бан хаммера задетектил на одном мак адресе поведение, то и на другом маке также забанят + повторная регистрация. Нужно выявить метрики пользователя сети, которые влияют на бан и пример действия для следующей волны.

**Comment by TheDrHax** [comment]
Конкретно с этой блокировкой мы разобрались. По поводу определения приложения создал отдельный тикет #163.
