### ISSUE TITLE
Нумерация версий

### ISSUE THREAD

**Issue by dimqua** [mosmetro-android/mosmetro-android#164]
Думаю, лучше начать нумеровать версии более очевидным образом. Сейчас у версии 1.7.7 целых три релиза. И лишь по номеру тега в репозитории (коду версии) можно понять какая из них последняя.

Возможно, следует делать бета-версии (1.7.7b1, 1.7.7b2) и/или релиз-кандидаты (1.7.7rc1, 1.7.7rc2). А теги могут соответствовать номеру версии. Если это, конечно, ничего не сломает.

**Comment by TheDrHax** [comment]
Сейчас практический смысл такой нумерации в том, что бету можно сделать публичной без изменения кода версии. То есть достаточно просто нажать одну кнопку в Google Play (beta -> production) и на GitHub (pre-release -> release) и текущая бета становится доступной для всех.

Можно просто всегда менять название версии, а код вообще спрятать, как это делают другие проекты. Например, в таблице перечислены два уже существующих релиза (и как они могли бы называться), а также следующий, если я его пропущу через бету и опубликую оттуда же.

| code | type | было | станет |
| -- | -- | -- | -- |
| 62 | бета | 1.8.0-62 | 1.8.0 |
| 63 | релиз | 1.8.0-63 | 1.8.1 |
| 64 | бета | 1.8.1-64 | 1.8.2 |
| 64 | релиз (из беты) | 1.8.1-64 | 1.8.2 |

Получается, что каждому version code будет соответствовать свой version name:

| code | name |
| -- | -- |
| 62 | 1.8.0 |
| 63 | 1.8.1 |
| 64 | 1.8.2 |

Ну и с альтернативными ветками всё станет гораздо лучше:

| code | branch | build | было | станет |
| -- | -- | -- | -- | -- |
| 62 | master | 123 | `master-#123-62` | `master-123` |
| 63 | master | 456 | `master-#456-63` | `master-456` |

Как насчёт такого?

**Comment by dimqua** [comment]
Делать релиз, не меняя код версии, можно не внося изменения в исходный код приложения. Но что если бета-версия окажется нестабильной и потребуется не один бета-выпуск, а несколько?

**Comment by TheDrHax** [comment]
Код версии обязательно надо менять для того, чтобы загрузить приложение в Google Play (не важно, релиз это или бета). При этом код всегда должен возрастать и быть уникальным и больше 0. Он указывается в build.gradle (и зашивается в APK), а также в тегах Git репозитория (они же релизы GitHub). Теги подхватываются F-Droid и собираются им автоматически. В общем, всё, кроме альтернативных веток, зависит от постоянно возрастающего кода версии.

А бета и так может быть нестабильной. В этом случае мы просто можем пропустить, например, 1.8.1 и следующая версия будет уже 1.8.2. Раньше я не менял название версии, чтобы нестабильные беты "исчезали" из истории и не вызывали недоумения у тех, кто пользуется релизной версией в Google Play.

**Comment by dimqua** [comment]
Думаю, если пользователь 1.8.0 получит обновление до 1.8.2, то это тоже вызовет у него недоумение. А почему не хотите делать буквенные (1.8.1b1 -> 1.8.1b2 -> 1.8.1) обозначения? Это исключительно для удобства, чтобы пользователь приложения мог определить какая версия у него установлена (бета или релиз) и до какой происходит обновление.

>Код версии обязательно надо менять

Но ведь Вы предложили не менять для 1.8.2?

**Comment by TheDrHax** [comment]
> Думаю, если пользователь 1.8.0 получит обновление до 1.8.2, то это тоже вызовет у него недоумение.

Вот именно поэтому беты и меняют название версии только один раз до следующего публичного релиза :)

> Это исключительно для удобства, чтобы пользователь приложения мог определить какая версия у него установлена (бета или релиз) и до какой происходит обновление.

По идее, если в Google Play включён бета-канал, то для пользователя нет никакой разницы, какая именно версия установлена. Мне кажется, что это так и было задумано: мы просто задерживаем публикацию релиза, делая его доступным для тех, кто согласился на более ранний доступ в новым версиям.

> Но ведь Вы предложили не менять для 1.8.2?

Так я написал, что там бета переходит в релиз без изменений. Загрузить новый APK с тем же кодом версии нельзя, а вот перенести уже загруженный из беты в релиз можно и даже удобно.

Да, я забыл уточнить, что коды версий едины для всех типов релизов. То есть у нас не может быть релиз с кодом 62, например, и бета с тем же кодом, но другим APK.

**Comment by dimqua** [comment]
>беты и меняют название версии только один раз

Но ведь это позволяет выпускать всего одну бета-версию (если я правильно понимаю), побуждая делать релизы чаще, от чего качество релизов _может_ страдать. И, _возможно_, что пользователи release-канала используют её, чтобы получать обновления реже, т.е. не против и 2-3 бета-версий между релизами.

>Загрузить новый APK с тем же кодом версии нельзя, а вот перенести уже загруженный из беты в релиз можно и даже удобно.

Тогда, по-моему, этот вариант лучше текущего. Но ведь обычно в релизе оказываются дополнительные изменения (исправления ошибок и т.п.), а придется от них отказаться.

**Comment by TheDrHax** [comment]
> Но ведь это позволяет выпускать всего одну бета-версию

Нет, каждая версия в любом случае меняет [код](https://github.com/mosmetro-android/mosmetro-android/blob/master/app/build.gradle#L12), но необязательно меняет [название](https://github.com/mosmetro-android/mosmetro-android/blob/master/app/build.gradle#L13).

Сейчас так и происходит: 1.8.0 (код 62), 1.8.0 (код 63), ... То есть бета версий 1.8.0 может быть сколько угодно и каждая из них может попасть в продакшен, если не будет критических багов. А вот после попадания в продакшен я перестаю выпускать новые вариации 1.8.0 и перехожу на 1.8.1.

Например, у версии 1.7.7 было 3 беты, последняя из которых стала основной (или вышла сразу, не помню уже).

Проще говоря, сейчас происходит вот это:

0. Определяем следующее название версии (например, 1.8.1)
1. Делаем изменения
2. Выпускаем новую бету (1.8.1, код = код + 1)
3. Если изменения что-то сломали: Возвращаемся на п. 1
4. Если всё в порядке: Выпускаем бету в общий доступ

При этом в [CHANGELOG](https://github.com/mosmetro-android/mosmetro-android/blob/master/CHANGELOG) эти циклы разделены при помощи `--`.

**Comment by dimqua** [comment]
Понял, спасибо. Но тогда получается, что сейчас 'код последней бета-версии' = 'код релиза', выше Вы предложили всем бета-версиям присвоить единый код. Зачем?

**Comment by TheDrHax** [comment]
> выше Вы предложили всем бета-версиям присвоить единый код

Хм... Такого я не предлагал, вроде.

Если речь идёт об этом фрагменте таблицы, то я говорил о том, что бета под кодом 64 стала в итоге публичной без изменений.

| code | type | было | станет |
| -- | -- | -- | -- |
| 64 | бета | 1.8.1-64 | 1.8.2 |
| 64 | релиз (из беты) | 1.8.1-64 | 1.8.2 |

Вообще, [это](https://github.com/mosmetro-android/mosmetro-android/issues/164#issuecomment-330194476) сообщение полностью описывает то, что я имею ввиду.

**Comment by dimqua** [comment]
> бета под кодом 64 стала в итоге публичной без изменений

А, значит сейчас код версии увеличивается перед выпуском релиза (из беты) и вносятся изменения, т.е. как при выпуске очередной бета-версии. Сразу этого не понял.

Тогда закрываю issue.

**Comment by TheDrHax** [comment]
Наиболее наглядно модель релиза можно увидеть в [Releases](https://github.com/mosmetro-android/mosmetro-android/releases) этого репозитория. Там отображается тип (release / pre-release) и тег (код версии). Каждый тег соответствует моменту загрузки APK в Google Play.

Я тогда пока не буду дублировать имена версий (1.8.0-63, 1.8.0-64) и уберу код версии из интерфейса, а то вопросы по этому поводу возникали уже. А в будущем (когда выйдет 2.0, если она выйдет) можно будет перейти на что-то принципиально новое (например, привязать код версии к названию и номеру сборки).
