### ISSUE TITLE
Модуль распознавания капчи не отвечает

### ISSUE THREAD

**Issue by TheDrHax** [mosmetro-android/mosmetro-android#166]
На некоторых устройствах модуль распознавания капчи не отвечает на запросы от приложения. Неизвестно, не успевает он или вообще не запускается.

Нужно найти какой-то другой способ взаимодействия между приложениями или разобраться с https://github.com/mosmetro-android/module-captcha-recognition/issues/4 и встроить модуль в основное приложение.

**Comment by OwnageIsMagic** [comment]
как вариант `startActivityForResult`

**Comment by OwnageIsMagic** [comment]
а лучше просто интегрировать этот модуль в основное приложение и скачивать модель по нажатию в меню

**Comment by TheDrHax** [comment]
@OwnageIsMagic Если это возможно сделать, то было бы удобно на первое время. Просто там сами библиотеки много места занимают, а я знаю только как assets докачивать. Делать сборки под разные архитектуры пока не вариант – придётся весь процесс сборки и публикации переделывать.

**Comment by OwnageIsMagic** [comment]
Classloader и его андроид друзья
https://stackoverflow.com/a/40179430

**Comment by OwnageIsMagic** [comment]
на самом деле даже класслоадер не нужен
там ява врапер крохотный и его можно статично подключить
главное не инстансировать его прежде чем скачали нативные либы

**Comment by TheDrHax** [comment]
Разработка модуля распознавания капчи приостановлена, так как самой капчи уже давно нет. Закрываю.
