### ISSUE TITLE
Новая блокировка автоподключения

### ISSUE THREAD

**Issue by LionZXY** [mosmetro-android/mosmetro-android#168]
При подключении каким-то образом обнаруживает приложение и запрещает вход. 
- [ ] Выяснить каким образом обнаруживает приложение 
- [ ] Придумать методы противодействия

**Comment by LionZXY** [comment]
![img_20170927_104703](https://user-images.githubusercontent.com/5871715/30901840-fbdff288-a371-11e7-862a-75d3eb16698a.jpg)

**Comment by TheDrHax** [comment]
Похожий тикет уже есть: #163
