### ISSUE TITLE
Вынос кода авторизации в отдельную библиотеку

### ISSUE THREAD

**Issue by petRUShka** [mosmetro-android/mosmetro-android#174]
Вынос кода авторизации в отдельную библиотеку, чтобы её можно было использовать в других программах. 

Например, очень не хватает автоматической авторизации для ноутбуков (linux, windows, mac os).

Если бы была бы библиотека, не привязанная к Android, то можно было бы написать простенький скрипт, её задействующий.

P.S. Собственно, чтобы автоматически работал проект типа [mosmetro-python](https://github.com/TheDrHax/mosmetro-python).

**Comment by OwnageIsMagic** [comment]
так уже вынесен
https://github.com/mosmetro-android/mosmetro-android/tree/master/app/src/main/java/pw/thedrhax/mosmetro/authenticator

**Comment by TheDrHax** [comment]
Я сначала пытался держать код Client и Provider отдельно от контекста Android, но это слишком неудобно. Если удалить лишние настройки, то отделить код -- не проблема. Но использовать его в приложении будет уже не так удобно.

Кажется, проще будет допилить mosmetro-python до актуального состояния. Там всё не настолько изменилось, если капчу во внимание не принимать.

**Comment by petRUShka** [comment]
Просто одно дело: держать одинаковый (по сути) код в двух проектах актуальным. А другое -- иметь общую библиотеку, когда всё в одном месте.

На первый взгляд, игра стоит свеч.

P.S. Может клиент сделать не python'овским, а java'вским?

**Comment by petRUShka** [comment]
Ну и допилить mosmetro было б мегаценно, конечно :)

**Comment by TheDrHax** [comment]
Если абстрагироваться от Android, то кода там не так уж и много. Особенно если из MosMetroV2 убрать все упоминания капчи, которой уже нет. Всего насчитал 4 запроса, между которыми происходит немного парсинга. Думаю, синхронизировать код Java и Python вручную можно без проблем :)

Я просто изначально Python-версию забросил из-за того, что парсинг HTML в ней производился комбинацией регулярных выражений и HTMLParser'а, которые очень трудно поддерживать. Можно вместо этого применить PyQuery и тогда код будет не сильно отличаться от того, что есть сейчас в MosMetroV2.

**Comment by petRUShka** [comment]
Верно ли я понял, что счастье настанет так (с библиотекой) или иначе (без библиотеки), т.к. вы планируете возродить mosmetro-python из пепла? :)

**Comment by TheDrHax** [comment]
Давно пора это сделать, так что постараюсь. Тем более, что по Python скучать начал, так как он шикарен :)

**Comment by petRUShka** [comment]
Очень жду! :)

**Comment by TheDrHax** [comment]
Это заняло гораздо меньше времени, чем я думал... Перенёс [mosmetro-python](https://github.com/mosmetro-android/mosmetro-python) в организацию.

Но там могут быть ошибки, так что буду рад увидеть результаты тестирования в будущем ;)

**Comment by petRUShka** [comment]
Вухууу!!!
