### ISSUE TITLE
Не может обойти блокировку

### ISSUE THREAD

**Issue by MaxAvatar007** [mosmetro-android/mosmetro-android#177]
Не может обойти блокировку, которая спокойно обходится через http://auth.wi-fi.ru/auth?segment=aeroexpress
![screenshot_20171025-195702](https://user-images.githubusercontent.com/8061587/32012037-53562452-b9bf-11e7-9b4f-8b201cd6073b.png)

**Comment by JacKeTUs** [comment]
@MaxAvatar007 В версии master-#297-67 блокировка прекрасно обходится приложением)

**Comment by TheDrHax** [comment]
В сборке master-295 настройка обхода блокировки была инвертирована, так что эта версия не пыталась их обходить по умолчанию. Это было исправлено в c8623a04de8c6cd6a61be2c00133ac7019d55926
