### ISSUE TITLE
Исключить ручное самостоятельное подключение к сети в метро

### ISSUE THREAD

**Issue by artbear** [mosmetro-android/mosmetro-android#182]
Приходится постоянно самостоятельно подключаться к сети в метро
Т.е. 
+ в уведомлениях появляются доступная сеть Mхх_Free - точное название не помню :)
+ или там написано "Требуется выполнить вход в сеть Mхх_Free"

Нажимаю на уведомление, открываются окно подключения к WiFi-сетям (просмотра всех доступных сетей).
Выбираю нужную сеть, нажимаю "Подключиться", и только после этого продукт начинает отрабатывать.

В документации не увидел описания подобной фичи.

Хотелось бы, чтобы при наличии обрабатываемых продуктов WiFi-сетей и наличии настройки автоподключения в настройках продукта выполнялось автоподключение нужной WiFi -сети.

**Comment by TheDrHax** [comment]
> или там написано "Требуется выполнить вход в сеть Mхх_Free"

Это было исправлено в #180. Но работает это исправление только на Android 5 и новее и с включённой привязкой к сети в настройках (включена по умолчанию в последних версиях).

> Выбираю нужную сеть, нажимаю "Подключиться", и только после этого продукт начинает отрабатывать.

Пока что так и должно быть. В данный момент приложение не управляет Wi-Fi и не участвует в сканировании доступных сетей.

Тикет #70 включает в себя пункт "Реализовать управление сохранёнными сетями Wi-Fi", который должен решить эту проблему. По умолчанию приложение не будет без ведома пользователя добавлять новые сети (это небезопасно), но можно будет сделать настройку, которая изменит это поведение.

В общем, этот тикет закрываю как повтор тикета #70. Когда-нибудь разберёмся с этим :)
