### ISSUE TITLE
Текст в уведомлениях

### ISSUE THREAD

**Issue by OwnageIsMagic** [mosmetro-android/mosmetro-android#184]
Сейчас все уведомления не разворачиваемые, и текст который не влез в ширину шторки не прочитать

**Comment by TheDrHax** [comment]
Оперативно :)

Да, есть такое, сейчас исправлю.

**Comment by OwnageIsMagic** [comment]
Лень резать скрины, поэтому под катом
<details>

![screenshot_2018-02-17-20-19-41-433_com miui home](https://user-images.githubusercontent.com/10534634/36427836-446fd0ee-165f-11e8-9926-77046e54d83f.png)


Развёрнутое


![screenshot_2018-02-17-20-19-52-393_com miui home](https://user-images.githubusercontent.com/10534634/36427871-5bf99af6-165f-11e8-9539-086629c081b2.png)

</details>
Версия 1.8.3.20-70
Android 6.0.1
Miui 8.1.2.0
