### ISSUE TITLE
Сброс регистрации устройства

### ISSUE THREAD

**Issue by gargullia** [mosmetro-android/mosmetro-android#193]
Каждый раз, при подключении, пишет "устройство не зарегистрировано" и просит заново пройти регистрацию.
Раз в сутки, или после перезагрузки устройства. Как выяснилось, привязывается мак адрес устройства, который при каждом включении устройства меняется по виду: `XX:XX:XX:aa:aa:aa` где ХХ постоянные цифры.
Прошивал на стоковые прошивки, кастомные, не лечиться. На девайсе где не было установлено приложение таких проблем нет.

**Comment by OwnageIsMagic** [comment]
в настройках wifi убери автоматическую смену мак адреса

**Comment by gargullia** [comment]
@OwnageIsMagic на nexus/pixel девайсах aosp, в стоковых и даже кастомных прошивках нету таких настроек.

**Comment by OwnageIsMagic** [comment]
В иос была настройка смены мака при сканировании сети
Может в андроидах такое тоже завезли
Без рута мак на андроиде не меняется
Похоже у вас что то такое
https://geektimes.ru/post/239939/

**Comment by TheDrHax** [comment]
Проблема заключается явно не в приложении, а в прошивке или Wi-Fi адаптере. Приложение пока не умеет менять MAC-адреса, да и прав у него таких нет (требуются права root). Закрываю, т.к. ничего с этим сделать не смогу.
