### ISSUE TITLE
Некорректная обработка таймаута в WebViewService

### ISSUE THREAD

**Issue by sleirsgoevy** [mosmetro-android/mosmetro-android#199]
При установке параметра pref_timeout в 0 попытка загрузки WebView приводит к немедленному появлению ошибки Synchronizer timed out, хотя значение pref_timeout == 0 обозначает отсутствие таймаута

**Comment by TheDrHax** [comment]
Теперь должно нормально работать. Хотя, скорее всего, конкретно этот таймаут скоро станет не нужен, т.к. я надеюсь перевести WebView на наш собственный клиент для большего контроля над запросами.
