### ISSUE TITLE
Не "Умирает" фоновое подключение

### ISSUE THREAD

**Issue by Faithfinder** [mosmetro-android/mosmetro-android#200]
При "ручном" режиме подключения, с ярлыком на подключение в фоновом режиме, приложение остаётся висеть в фоне после успешного подключения и мониторит сети. Самый верный способ отключить - нажать "закрыть все" в... Не знаю как это называется, там где открытые приложения переключаются.
Андроид 7.0, Xiaomi Mi Max, прошивка от miui.su

**Comment by TheDrHax** [comment]
Уведомление пропадает, но приложение продолжает отображаться в списке запущенных процессов, да? Просто эта проблема когда-то давно уже обсуждалась в группе Telegram, но решение тогда найти не удалось. В итоге мы пришли к выводу, что это Android так "кэширует" фоновые процессы, чтобы не запускать их повторно.

На эмуляторе это тоже воспроизводится, но у фонового процесса стабильно срабатывает метод `onDestroy()`, т.е. объект уничтожается, а процесс остаётся и ничего не делает. По идее, такой процесс не должен тратить заряд аккумулятора и будет завершён при нехватке памяти.

Может кто-нибудь ещё об этом слышал? Это я что-то не доделал или завершить процесс можно только костылями вроде `kill`?

**Comment by Faithfinder** [comment]
Нет, уведомление тоже не пропадает. Работает как если бы автоподключение было включено, но закрывается, если закрыть все, и иногда (не стабильно), если открыть основное приложение и закрыть его

**Comment by TheDrHax** [comment]
В таком случае может помочь лог подключения. Его можно достать через уведомление (которое не пропадает). Обычно в логе содержатся все события Wi-Fi и фонового процесса.

Отправьте лог сюда или ко мне на почту (с упоминанием #200 в теме), когда фоновый процесс снова откажется завершаться. Возможно, что в нём будет что-то полезное.

**Comment by Faithfinder** [comment]
[pw.thedrhax.mosmetro.txt](https://github.com/mosmetro-android/mosmetro-android/files/1858929/pw.thedrhax.mosmetro.txt)
Вот. Могу предположить, что виновата галочка "Переподключаться" в настройках подключения, но явно же не нормально что я из метро вышел час назад, а процесс все ещё висит :)

**Comment by TheDrHax** [comment]
Судя по сообщению `Started by system`, автоподключение активно. Но при этом не видно событий Wi-Fi от системы, т.е. оно всё-таки неактивно.

Это может означать, что используемый ярлык остался от старой версии и не совместим с текущей. С таким ярлыком фоновый процесс будет сам проверять, подключено ли устройство к нужной сети, а потом ждать сообщение от системы, что Wi-Fi отключился (а оно не придёт без автоподключения).

Можно попробовать отключить Wi-Fi и воспользоваться ярлыком: если в уведомлениях ничего не появится (даже на долю секунды), то ярлык неисправен и нужно его пересоздать.

**Comment by Faithfinder** [comment]
Вообще ярлык создавал в одной из последних версий, не больше месяца-двух назад, до этого пользовался автоподключением (пока банить не начали. С ручным тоже банят, но не так часто).
Но пересоздать не проблема, так что просто взял и пересоздал его сейчас.
Новый ярлык на нажатия не реагирует, да. Но я не в метро, по дороге домой ещё раз попробую.

[pw.thedrhax.mosmetro (2).txt](https://github.com/mosmetro-android/mosmetro-android/files/1863243/pw.thedrhax.mosmetro.2.txt)
Не уверен что это зачем-то надо, но вот лог процесса, провисевшего всю ночь (до смены ярлыка)

**Comment by Faithfinder** [comment]
Наконец вспомнил зайти и отписаться. Есть впечатление что фоновое в новой версии работает не очень стабильно, значок появляется, исчезает, но интернет начинает работать через раз. В итоге я перешел на нефоновое - всё равно пока инет не подключится открываю шторку и пялюсь на процесс подключения. Тем не менее проблему с висящим процессом пересоздание ярлыка решило, так что этому тикету жить больше точно незачем.
