### ISSUE TITLE
Doens't work in the ground transport of spb.

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [mosmetro-android/mosmetro-android#205]
Works in subwaway but not in trams and buses of the Saint-Petersburg.

More logs should be provided.

**Comment by TheDrHax** [comment]
This should have been fixed by #208 (since build [master-#351](https://jenkins.thedrhax.pw/job/mosmetro-android-pipeline/job/master/351/)). Please reopen this issue if the problem still persists.
