### ISSUE TITLE
Работа приложения на Android P

### ISSUE THREAD

**Issue by l0rus** [mosmetro-android/mosmetro-android#207]
1. Не срабатывает создание уведомления о подключении
2. Не определяется наименование сети ( Подключение к сети <unknown since ssid> )

Девайс - Google Pixel
Версия Android - P (сборка PPP2. 180412.013)
Версия приложения - master-#349-70

**Comment by TheDrHax** [comment]
Похоже, что эти проблемы связаны с новым SDK. Вот тут основное обсуждение и план действий: #197
