### ISSUE TITLE
 master #359 - Ошибка: устройство не зарегистрировано в сети

### ISSUE THREAD

**Issue by xidalo** [mosmetro-android/mosmetro-android#210]
Android 5.1

Версия  master #359 выдает ошибку **Ошибка: устройство не зарегистрировано в сети**
Версия master-#350-70 подключается без проблем.

Логи
master-350: https://yadi.sk/i/MRiF5ANI3aN5un
master-359: https://yadi.sk/i/MC23BAYx3aN5yD

**Comment by xidalo** [comment]
> Если после ошибки в #359 вернуться на #350, то всё работает?

Вечером 359 и 350 выдавали эту ошибку, а утром 359 выдала ошибку а 350 заработала

>В таком случае либо на обеих версиях будет работать, либо не будет.

Тем не менее 350 использует MosMetroV2, а 359 - MosMetroV3. 
Может они разные MAC посылают.

**Comment by TheDrHax** [comment]
> Тем не менее 350 использует MosMetroV2, а 359 - MosMetroV3.

Хм, да. Это, похоже, единственное различие между ними. Сборки до #351 игнорировали перенаправление на MosMetroV3 и подключались сразу к MosMetroV2. Это работало до недавних пор, однако в Санкт-Петербурге что-то поменяли и MosMetroV3 стал необходим для подключения

Проблема в том, что ни один из алгоритмов не определяет и не посылает MAC. Его определяет точка доступа, передаёт информацию провайдеру, а уже потом провайдер встраивает MAC в страницу, чтобы устройство передавало его вместе со следующими запросами. (Ну или страницей входа занимается сама точка доступа, мы этого не узнаем.) Т.е. ни браузер, ни приложение MAC адресами не занимаются.

Поэтому интересно, потребуется ли регистрация при подключении через браузер? По сути, MosMetroV3 действует в точности как браузер (иначе не работало бы в СПб), поэтому через браузер без регистрации зайти не удастся (в теории).

Но я всё-таки думаю, что это у них база данных упала. Бывало уже такое :)

**Comment by xidalo** [comment]
Можно сделать версию с двумя опциями - V3 и V2? Или использовать V2 если V3  не получилось?

Допускаю, что пока я удалял 359 и ставил 350 база заработала.
Но хочется  исключить влияние перестановок и проверять подключение разными методами за короткий промежуток  времени.

**Comment by TheDrHax** [comment]
Кстати, забыл упомянуть. После MosMetroV3 всегда обязательно запускается MosMetroV2. В сам алгоритм входит процедура переключения на другой алгоритм. То есть MosMetroV3 необходим в СПб, но не достаточен для подключения к интернету.

**Comment by xidalo** [comment]
toggle_v3 #2
https://yadi.sk/i/waSpKRc63aUR2J
Он пытался авторизоваться на v3? Ошибки не было -  почему он перешел на v2

master-#349-70 - успешно. Был момент поиска сети телефоном
https://yadi.sk/i/kQGRSQkG3aURBq

**Comment by TheDrHax** [comment]
Удивительно! Похоже, что MosMetroV3 действительно как-то влияет на дальнейшее подключение. Это не очень хорошие новости, т.к. теперь надо искать, в чем же эти два подключения различаются.

* Не пробовали ли вы отключить MosMetroV3 в главном меню сборки _toggle_v3? В теории, поведение сборки _toggle_v3 должно совпасть с master #349, т.к. MosMetroV3 отключается, а в MosMetroV2 возвращается обход welcome.wi-fi.ru, который был удалён в master #351. Тогда не придётся возвращаться на master ради проведения теста;

* Также интересно, что получится, если зайти просто через браузер. Если это не какое-то аномальное поведение в приложении, то в браузере должна появиться та же ошибка с регистрацией;

* Только что вышла [3-я сборка](https://jenkins.thedrhax.pw/job/mosmetro-android-pipeline/job/_toggle_v3/3/artifact/SignApksBuilder-out/android-keystore/pw.thedrhax.*/MosMetro-_toggle_v3-v70-b3-unsigned.apk/MosMetro-_toggle_v3-v70-b3.apk) _toggle_v3, в которую я перенес изменения алгоритма MosMetroV3 из master. Возможно, что эта ошибка также будет исправлена. Маловероятно, но проверить стоит;

Возможно, что с помощью этих трех тестов удастся понять, в чём проблема.

---

> Ошибки не было - почему он перешел на v2

Так и должно быть. В предыдущем сообщении писал об этом, MosMetroV3 — вспомогательный алгоритм, который затем сводится к одному из других алгоритмов.

**Comment by xidalo** [comment]
Я остаюсь на 349

_toggle_v3 #3 - неуспешно https://yadi.sk/i/Pa8lEEvj3aZsej
потом master-#349-70 : Уже подключено - устройство не зарегистрировано в сети - успешно https://yadi.sk/i/s5ynODWw3aZsft

master #362 - Устройство не зарегистрировано в сети https://yadi.sk/i/I2UKo22g3aZsh4
master-#349-70 - Успешно https://yadi.sk/i/6RKZAndP3aZshk
