### ISSUE TITLE
WiFi в МАИ

### ISSUE THREAD

**Issue by SlimRG** [mosmetro-android/mosmetro-android#214]
В МАИ есть бесплатная сеть MAInet_public 
Логин MAI
Пароль 1930

**Comment by SlimRG** [comment]
POST https://wifi.mai.ru/login.html HTTP/1.1
Host: wifi.mai.ru
Connection: keep-alive
Content-Length: 160
Cache-Control: max-age=0
Origin: https://wifi.mai.ru
Upgrade-Insecure-Requests: 1
DNT: 1
Content-Type: application/x-www-form-urlencoded
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Referer: https://wifi.mai.ru/login.html?redirect=https://yandex.ru/search/
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en;q=0.8,en-US;q=0.7

buttonClicked=4&err_flag=0&err_msg=&info_flag=0&info_msg=&redirect_url=https%3A%2F%2Fyandex.ru%2Fsearch%2F&network_name=Guest+Network&username=MAI&password=1930

**Comment by SlimRG** [comment]
SSID:	MAInet_public
Протокол:	802.11n
Тип безопасности:	Открытая
Диапазон сети:	5 ГГц
Канал сети:	161
IPv4-адрес:	172.31.213.144
DNS-серверы IPv4:	172.16.0.130
172.31.0.2
Изготовитель:	Qualcomm Atheros Communications Inc.
Описание:	Qualcomm Atheros AR5BWB222 Wireless Network Adapter
Версия драйвера:	10.0.3.456
Физический адрес (MAC):	68-94-23-79-85-49

**Comment by SlimRG** [comment]
Cеть уже 2й год работает с этой конфигурацией

**Comment by TheDrHax** [comment]
Ах да, вспомнил кое-что. Мне ещё нужно перенаправление, которое сеть возвращает, если в ней не залогиниться. Сейчас приложение уже не ориентируется на SSID, а анализирует ответ с, например, http://google.com/generate_204

**Comment by SlimRG** [comment]
Попробую завтра записать сессию Fiddler

**Comment by SlimRG** [comment]
http://images.vfl.ru/ii/1543301210/05c23620/24368814.png

**Comment by SlimRG** [comment]
http://images.vfl.ru/ii/1543301284/5cb41799/24368819.png

**Comment by SlimRG** [comment]
Вот, редиректы

**Comment by SlimRG** [comment]
Не смог текстом, т.к. программа Free

**Comment by SlimRG** [comment]
Если нужно - скину архив пакетов Fiddler, но не раньше четверга

**Comment by SlimRG** [comment]
Да, только один POST запрос
Студенты МАИ будут вам очень благодарны
:)

**Comment by TheDrHax** [comment]
@SlimRG Спасибо! Тут всё видно. Постараюсь сегодня/завтра сделать отдельную ветку, проверим её и потом солью с master :)

**Comment by TheDrHax** [comment]
Сделал тестовую сборку: https://mosmetro.duckdns.org/api/v1/download.php?branch=MAInet_public

Она основана не на master, а на mcc-rm, в которой несколько удобных штук реализовано. Так что сначала нужно будет доделать mcc-rm, а потом уже переносить этот алгоритм в основную версию. Как раз проверить его успеем)

**Comment by SlimRG** [comment]
Спасибо - завтра проверю

**Comment by SlimRG** [comment]
Увы - приболел
Отчитаюсь попозже

**Comment by SlimRG** [comment]
Не фурычит

**Comment by TheDrHax** [comment]
@SlimRG А можно лог подключения? Главное меню – Ручное подключение – кнопка-конверт наверху. Только старый лог не сохранился, скорее всего. Надо новый.

**Comment by SlimRG** [comment]
https://yadi.sk/i/TDn8SLL5RmILbw

**Comment by TheDrHax** [comment]
@SlimRG Ой, там опечатка в URL. Сейчас 2-я сборка выйдет. https://jenkins.thedrhax.pw/job/mosmetro-android-pipeline/job/MAInet_public/2/

**Comment by SlimRG** [comment]
https://yadi.sk/d/QKz5XgjTcD4kbg

**Comment by SlimRG** [comment]
Пакеты разделены пустой строкой

**Comment by SlimRG** [comment]
Все - заработало

**Comment by SlimRG** [comment]
https://yadi.sk/i/TDn8SLL5RmILbw

**Comment by TheDrHax** [comment]
Отлично! Этот тикет закрою, когда изменения попадут в master. Спасибо за информацию о сети :)

**Comment by SlimRG** [comment]
Сейчас все захотели проверить программу - уронили сервак MAInet :innocent:

**Comment by SlimRG** [comment]
Завтра думаю поднимут сервак - отпишусь ^_^

**Comment by SlimRG** [comment]
Щас зашёл в Маевский парк - там тот же SSID, все коннектит
Огромное вам спасибо
