### ISSUE TITLE
Требуется разрешение от автора

### ISSUE THREAD

**Issue by SlimRG** [mosmetro-android/mosmetro-android#230]
Добрый вечер!
Очень впечатлил ваш проект, огромное вам спасибо!

Прошу дочитать до конца и только после писать на тему "извращенец".

Итак, я в основном специализируюсь на безопасности, как хобби люблю прогать на Delphi. 

Ваше приложение мне очень понравились, как я уже писал. Но у него есть, по моему несколько недостатков, сугубо личного характера.

А именно:
1) Отсутствие кроссплатформенности
2) Скудная база данных сетей
3) Сложное вхождение для разработки (пока все настроишь - повеситься можно, ну или выпить 8 чашек кофе, как я)
4) Для обновления алгоритма требуется обновлять ВСЮ программу
И т.д. и т.п.

Но проект очень хотелось бы расширить и пустить в массы :3

Как итог я хотел бы создать свой проект на Delphi, берущий некоторые алгоритмы из вашего.

Для этого, ну и для приличия, нужно разрешение автора.

Собственно этого я у вас и прошу.

**Comment by SlimRG** [comment]
Также я смогу задействовать идею с обходом блокировки через подмену нулевым mac

**Comment by TheDrHax** [comment]
Без проблем :)

Сами алгоритмы, по сути, лежат в открытом доступе — достаточно лишь снять дамп обычного подключения через браузер и повторить в коде. Так что у меня тут и так не слишком много оригинальности.

А перечисленные недостатки связаны с тем, что проект изначально был заточен под Android и создавался на основе шаблона из Android Studio. Сейчас будет довольно сложно его разделить на независимые модули, поэтому и держу всё в одном репозитории.

Вообще, я планировал когда-нибудь сделать загружаемые алгоритмы, но для этого надо либо придумать какой-то свой скриптовый язык программирования, либо использовать что-то вроде Lua и прокинуть туда основные интерфейсы из Java. Учитывая, сколько осталось нерешенных проблем, я ещё нескоро до этого дойду.

На всякий случай напомню, что есть [альтернативный проект на Python](https://github.com/mosmetro-android/mosmetro-python), который давно не обновлялся. В нём реализован только алгоритм MosMetroV2 и тот частично. По идее, можно было бы его попробовать улучшить. Но если на Delphi получится проще, то почему бы и нет?)

**Comment by TheDrHax** [comment]
> Также я смогу задействовать идею с обходом блокировки через подмену нулевым mac

А вот это, кстати, можно реализовать и с текущими версиями приложения. Для этого нужен Tasker или любой другой автоматизатор. Дело в том, что приложение [рассылает Intent](https://github.com/mosmetro-android/mosmetro-android/wiki/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-Tasker-%D0%B8%D0%BB%D0%B8-%D0%B4%D1%80%D1%83%D0%B3%D0%B8%D1%85-%D0%B0%D0%B2%D1%82%D0%BE%D0%BC%D0%B0%D1%82%D0%B8%D0%B7%D0%B0%D1%82%D0%BE%D1%80%D0%BE%D0%B2-%D0%B2%D0%BC%D0%B5%D1%81%D1%82%D0%B5-%D1%81-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5%D0%BC) `pw.thedrhax.mosmetro.event.MosMetroV2.BANNED`, если замечает, что устройство было заблокировано. А уже с помощью Tasker можно делать что угодно, в том числе и MAC менять.

**Comment by SlimRG** [comment]
Отлично - огромное спасибо!
