### ISSUE TITLE
Тёмная тема 

### ISSUE THREAD

**Issue by gabolaev** [mosmetro-android/mosmetro-android#233]
Сделайте возможность переключиться на тёмную тему) А то Android 10 dark mode вышел, а самое хацкерское приложение до сих пор белое)

**Comment by bvn13** [comment]
А зачем? Ты его вообще открываешь? Дай больше привилегий приложению, автозапуск и забудь про него - само будет подключаться.

**Comment by IRainman** [comment]
Уже есть #225 :)
